# Generated by Django 3.2.15 on 2023-03-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20230302_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conent',
            new_name='content',
        ),
    ]
