# Generated by Django 3.2.9 on 2023-03-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_rename_conent_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=200),
        ),
    ]
