# Generated by Django 3.2.9 on 2023-03-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20230306_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.CharField(default='/static/img/news-1.jpg', max_length=200),
        ),
    ]
