# Generated by Django 3.2.9 on 2023-03-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_id_no'),
        ('BlogApp', '0005_alter_news_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.user'),
        ),
    ]
