# Generated by Django 3.2.9 on 2023-03-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_id_no'),
        ('BlogApp', '0006_post_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_like',
            field=models.ManyToManyField(blank=True, null=True, to='UserApp.User', verbose_name='点赞用户'),
        ),
        migrations.AlterField(
            model_name='post',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonguser', to='UserApp.user'),
        ),
    ]
