# Generated by Django 3.2.9 on 2023-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_id_no'),
        ('BlogApp', '0007_auto_20230316_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_like',
            field=models.ManyToManyField(blank=True, to='UserApp.User', verbose_name='点赞用户'),
        ),
    ]
