# Generated by Django 3.2.9 on 2023-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_alter_post_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.TextField(default='/static/img/news-1.jpg'),
        ),
    ]
