# Generated by Django 3.2.9 on 2023-03-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('user_age', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=20)),
                ('relative_name', models.CharField(max_length=20)),
                ('relative_sex', models.CharField(max_length=20)),
                ('relative_age', models.CharField(max_length=20)),
                ('relative_height', models.CharField(max_length=20)),
                ('relative_weight', models.CharField(max_length=20)),
                ('relative_allergy', models.CharField(max_length=20)),
                ('relative_illness', models.CharField(max_length=20)),
                ('relative_surgery', models.CharField(max_length=20)),
                ('relative_injury', models.CharField(max_length=20)),
                ('disability', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Health_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_height', models.FloatField()),
                ('user_weight', models.FloatField()),
                ('allergy', models.CharField(max_length=20)),
                ('illness', models.CharField(max_length=20)),
                ('surgery', models.CharField(max_length=20)),
                ('injury', models.CharField(max_length=20)),
                ('family_history', models.CharField(max_length=20)),
                ('genetic_disease', models.CharField(max_length=20)),
                ('disability', models.CharField(max_length=20)),
                ('common_drugs', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
    ]
