# Generated by Django 3.2.9 on 2023-03-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(null=True),
        ),
    ]
