# Generated by Django 3.2.9 on 2023-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
