# Generated by Django 3.2.9 on 2023-03-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('chief_complaint', models.CharField(max_length=20)),
                ('HPI', models.CharField(max_length=20)),
                ('PH', models.CharField(max_length=20)),
                ('diagnose', models.CharField(max_length=20)),
                ('prescription', models.CharField(max_length=20)),
                ('DA', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('infoid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('user_age', models.CharField(max_length=20)),
                ('user_height', models.FloatField()),
                ('user_weight', models.FloatField()),
                ('allergy', models.CharField(max_length=20)),
                ('illness', models.CharField(max_length=20)),
                ('disability', models.CharField(max_length=20)),
                ('common_drugs', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PEinfo',
            fields=[
                ('PEid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('items', models.CharField(max_length=20)),
                ('blood_sugar', models.CharField(max_length=20)),
                ('total_cholesterol', models.CharField(max_length=20)),
                ('triglyceride', models.CharField(max_length=20)),
                ('minimum', models.CharField(max_length=20)),
                ('maximum', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
    ]
