# Generated by Django 3.2.9 on 2023-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_peinfo_userinfo_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='peinfo',
            name='hospital',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
