# Generated by Django 3.2.9 on 2023-03-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_peinfo_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='data',
            new_name='date',
        ),
    ]
