# Generated by Django 3.2.9 on 2023-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_rename_data_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='peinfo',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
