# Generated by Django 3.2.9 on 2023-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_peinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='states',
            field=models.IntegerField(default=1),
        ),
    ]
