# Generated by Django 3.2.9 on 2023-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_user_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peinfo',
            name='items',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='allergy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='common_drugs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='disability',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='illness',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='DA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='HPI',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='PH',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='chief_complaint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescription',
            field=models.CharField(max_length=255),
        ),
    ]
