# Generated by Django 3.2.9 on 2023-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20230416_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='disability',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_allergy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_illness',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_injury',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_surgery',
            field=models.CharField(max_length=255),
        ),
    ]
