# Generated by Django 3.2.9 on 2023-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_auto_20230416_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='common_drugs',
            field=models.CharField(default='无', max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='allergy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='common_drugs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='disability',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='family_history',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='genetic_disease',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='illness',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='injury',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='health_doc',
            name='surgery',
            field=models.CharField(max_length=255),
        ),
    ]
