# Generated by Django 3.2.9 on 2023-04-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_auto_20230416_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Re_Visit',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('HPI', models.CharField(max_length=255)),
                ('PH', models.CharField(max_length=255)),
                ('diagnose', models.CharField(max_length=255)),
                ('prescription', models.CharField(max_length=255)),
                ('DA', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.relative')),
            ],
        ),
        migrations.CreateModel(
            name='Re_PEinfo',
            fields=[
                ('PEid', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=255)),
                ('blood_sugar', models.CharField(max_length=20)),
                ('total_cholesterol', models.CharField(max_length=20)),
                ('triglyceride', models.CharField(max_length=20)),
                ('minimum', models.CharField(max_length=20)),
                ('maximum', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
                ('date', models.DateTimeField(null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.relative')),
            ],
        ),
    ]
