# Generated by Django 4.2.11 on 2024-04-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_auto_20230416_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': '爬取内容',
                'verbose_name_plural': '爬取内容',
            },
        ),
    ]
