# Generated by Django 4.2.11 on 2024-04-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_crawledcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawledcontent',
            options={},
        ),
    ]
