# Generated by Django 3.2.9 on 2023-03-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('doctor_sex', models.CharField(max_length=20)),
                ('doctor_age', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),

            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('user_age', models.CharField(max_length=20)),
                ('symptom', models.CharField(max_length=20)),
                ('diagnose', models.CharField(max_length=20)),
                ('Rp', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('conent', models.TextField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.doctor')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('conent', models.TextField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.doctor')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
    ]
