# Generated by Django 3.2.9 on 2023-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='r_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
