# Generated by Django 3.2.9 on 2023-03-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0002_auto_20230302_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='conent',
        ),
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='r_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Rp',
            field=models.CharField(max_length=200),
        ),
    ]
