# Generated by Django 3.2.9 on 2023-03-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_id_no'),
        ('DoctorApp', '0003_auto_20230308_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='department',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_sex',
        ),
        migrations.AddField(
            model_name='recipe',
            name='d_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.doctor'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='deid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.department'),
        ),
    ]
