# Generated by Django 3.2.9 on 2023-03-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0004_auto_20230308_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='s_time',
            field=models.CharField(max_length=20),
        ),
    ]
