# Generated by Django 3.2.9 on 2023-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0005_auto_20230308_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='introduce',
            field=models.TextField(null=True),
        ),
    ]
