# Generated by Django 3.2.9 on 2023-03-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0006_department_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='conent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='u_id',
        ),
        migrations.AddField(
            model_name='consult',
            name='drugs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consult',
            name='howlong',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consult',
            name='r_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.recipe'),
        ),
        migrations.AddField(
            model_name='consult',
            name='target',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
