# Generated by Django 3.2.9 on 2023-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0007_auto_20230315_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
