# Generated by Django 3.2.9 on 2023-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0008_consult_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
