# Generated by Django 3.2.9 on 2023-03-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0009_alter_consult_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Rp',
            field=models.TextField(),
        ),
    ]
