# Generated by Django 3.2.9 on 2023-03-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0010_alter_recipe_rp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='good_at',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
