# Generated by Django 3.2.9 on 2023-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0011_doctor_good_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.TextField(default='0'),
        ),
    ]
