# Generated by Django 3.2.9 on 2023-04-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0012_register_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='state',
            new_name='status',
        ),
    ]
