# Generated by Django 3.2.9 on 2023-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0013_rename_state_consult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
