# Generated by Django 3.2.9 on 2023-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0014_alter_consult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='states',
            field=models.IntegerField(default=1),
        ),
    ]
