# Generated by Django 3.2.9 on 2023-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0015_doctor_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='states',
            field=models.IntegerField(default=0),
        ),
    ]
