# Generated by Django 3.2.9 on 2023-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0016_alter_doctor_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.TextField(default='/static/img/profile-img.jpg'),
        ),
    ]
