# Generated by Django 3.2.9 on 2023-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0017_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='good_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diagnose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='symptom',
            field=models.CharField(max_length=255),
        ),
    ]
