# Generated by Django 4.2.11 on 2024-05-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0018_auto_20230416_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='keshi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
