# Generated by Django 3.2.9 on 2023-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('manager_sex', models.CharField(max_length=20)),
                ('manager_age', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
