# Generated by Django 3.2.9 on 2023-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_alter_manager_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='states',
            field=models.IntegerField(default=1),
        ),
    ]
